src/PersonalManagementSystem/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from homeapp.views import homepage_view
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',homepage_view),

# ]
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView
from dashboard.views import dashboard_view
from todolist.views import CreateToDoListView, taskJson, deleteJson, markItemAsCompleted, editTask
from issues.views import IssueView, issuesJson, deleteIssue, editIssue
from issues.views import IssueView
from passwords.views import PasswordView, deletePassword, updatePassword
from schedules.views import ScheduleView
from bills.views import BillsView, deleteBill
from schedules.views import ScheduleView, deleteSchedule, editSchedule

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('dashboard/',include('dashboard.urls')),

    path('todolist/',CreateToDoListView.as_view()),
    path('todolist/json/<int:task>',taskJson,name='taskJson'),
    path('todolist/delete/<int:task>',deleteJson,name='deleteJson'),
    path('todolist/update/<int:task>',markItemAsCompleted,name='markItemAsCompleted'),
    path('todolist/edit/<int:task>',editTask,name='editTask'),

    path('issues/',IssueView.as_view()),
    path('issues/json/<int:issue>',issuesJson,name='issuesJson'),
    path('issues/delete/<int:issue>',deleteIssue,name='deleteIssue'),
    path('issues/edit/<int:issue>',editIssue,name='editIssue'),

    path('passwords/',PasswordView.as_view()),
    path('passwords/delete/<int:password>',deletePassword,name='deletePassword'),
    path('passwords/update/<int:password>',updatePassword,name='updatePassword'),

    path('schedules/',ScheduleView.as_view()),
    path('schedules/delete/<int:schedule>',deleteSchedule,name='deleteSchedule'),
    path('schedules/edit/<int:schedule>',editSchedule,name='editSchedule'),

    path('bills/',BillsView.as_view()),
    path('bills/delete/<int:bill>',deleteBill,name='deleteBill'),

   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

src/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

src/dashboard/urls.py
from django.urls import path
app_name = 'dashboard'
from dashboard.views import dashboard_view,urlBillsPerMonth
urlpatterns = [
    path('main/', dashboard_view, name='dashboard_page'),
    path('main/year/<int:specified_year>',urlBillsPerMonth,name='specific_year'),
]

src/main/views.py
from django.views.generic import TemplateView


class IndexPageView(TemplateView):
	
    template_name = 'main/index.html'


class ChangeLanguageView(TemplateView):
    template_name = 'main/change_language.html'

src/content/templates/main/change_language.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% get_current_language as language_code %}
    {% get_available_languages as languages %}

    <h4>{% trans 'Change language' %}</h4>

    <form action="{% url 'set_language' %}" method="post">

        {% csrf_token %}

        <input name="next" type="hidden" value="{{ redirect_to }}"/>

        <div class="form-group">
            <label class="form-control-label" for="language-field">{% trans 'Select the language' %}</label>
            <select name="language" class="form-control" id="language-field">
                {% for code, name in languages %}
                    <option value="{{ code }}" {% if code == language_code %} selected="selected"{% endif %}>
                        {{ name }} ({{ code }})
                    </option>
                {% endfor %}
            </select>
        </div>

        <button class="btn btn-success">{% trans 'Change' %}</button>

    </form>

{% endblock %}

src/content/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Homepage</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png'%}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">
  <style>
    #about
    {
      margin-top:9.5rem;
    }
  </style>
  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css''%}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1><a href="/"><img src="{% static 'assets/img/logo1.png' %}" alt="" class="img-fluid"></a><a href="/">Personal Management System</a></h1>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="active" href="/">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#featured">Features</a></li>
          <li><a href="#footer">Contact Us</a></li>
      </nav>

    </div>
  </header>
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active" style="background: url({% static 'assets/img/slide/slide-1.jpg'%})">
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Personal Management System<span><br>For Educators</span></h2>
                <p class="animate__animated animate__fadeInUp">Personal Management System for Educators is a web-app tool designed to organize the essentials of everyday life. It can help you do everything from keeping a simple to-do list to managing schedules. No more thinking about unhandled pending issues, no more sticky notes on the desk, or missing out on important deadlines.</p>
                {% if request.user.is_authenticated %}
                  <a href="{% url 'dashboard:dashboard_page' %}" class="btn-get-started animate__animated animate__fadeInUp">Go to Dashboard</a>
                  <a href="{% url 'accounts:log_out' %}" class="btn-get-started animate__animated animate__fadeInUp">Log Out</a>
                {% else %}
                  <a href="{% url 'accounts:sign_up' %}" class="btn-get-started animate__animated animate__fadeInUp">Sign Up</a>
                  <a href="{% url 'accounts:log_in' %}" class="btn-get-started animate__animated animate__fadeInUp">Login</a>
                 {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="row">
          <div class="col-lg-6">
            <img src="{% static 'assets/img/abou1.jpg'%}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content">
            <h3>Simplicity, transparency, flexibility and expandability - designed for personal use.</h3>
            <p class="font-italic">
              All educators have various tasks, personal commitments, and deadlines to meet. In such a stressful environment, being organised is the key to efficiency and success. Our system offers a variety of tools designed with the following goals in mind:
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i>Your central point for managing personal data.</li>
              <li><i class="bi bi-check-circle"></i>Freedom of mind - keep control of schedules, notes, to-do lists all in one place.</li>
              <li><i class="bi bi-check-circle"></i>Intuitive and user-friendly - designed to be clear and handy so that everything is organized and divided into the proper categories and subsections.</li>
            </ul>
            <p>
              With this Management System, we hope to provide you all the support you need in managing your day-to-day activities. It will be our endeavour to keep improving your experience with this system as we go along.
            </p>
          </div>
        </div>

      </div>
    </section>
    <!-- End About Section -->

    <!-- ======= Featured Section ======= -->
    <section id="featured" class="featured">
      <div class="container">

        <div class="row">
          <a href="/todolist"><div class="col-lg-4">
            <div class="icon-box">
              <i class="bi bi-card-checklist"></i>
              <h3><a href="/todolist">To-Do List</a></h3>
              <p>By keeping such a list, you make sure that your tasks are all in one place so you don't forget anything important. </p>
            </div></a>
          </div>
          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="icon-box">
              <i class="bi bi-calendar-check"></i>
              <h3><a href="">Schedules</a></h3>
              <p>Keep track of everyday schedules or any recurring things you have to do. You can avoid clashes by prioritizing tasks.</p>
            </div>
          </div>
          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="icon-box">
              <i class="bi bi-exclamation-circle"></i>
              <h3><a href="/issues">Issues</a></h3>
              <p>These include any ongoing/pending cases that have to be eventually resolved but it's not necessary to keep a constant eye on them. </p>
            </div>
          </div>
        </div>
        <br><br>
          <div class="row second">
          <a href="/passwords"><div class="col-lg-4 mt-4 mt-lg-0">
            <div class="icon-box">
              <i class="bi bi-key"></i>
              <h3><a href="/passwords">Passwords</a></h3>
              <p>With the Passwords module, you can keep your passwords encrypted in the database, and look up the original password whenever required.</p>
            </div>
          </div>
          <div class="col-lg-4 mt-4 mt-lg-0">
            <div class="icon-box">
              <i class="bi bi-credit-card"></i>
              <h3><a href="">Bills & Payments</a></h3>
              <p>Keep track of recurring payments and see monthly summary of the expenses incurred on various categories of expenditure.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Featured Section -->
  </main>
  <!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              Mukesh Patel School of Technology <br>Management and Engineering  <br>
              Vile Parle<br>
              Mumbai <br><br>
              <strong>Phone:</strong> +91 7738550560<br>
              <strong>Email:</strong> pms.educators@gmail.com<br>
            </p>

          </div>

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>About Us</h3>
            <p>This project was developed as a part of the software engineering course offered by our institution.<br>The motivation behind this system was to be able to create a tool that helps our professors. </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>PMSeducators</span></strong>. All Rights Reserved
      </div>
    </div>
  </footer>
  <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter.js'%}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js'%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js'%}"></script>

</body>

</html>

src/content/templates/main/index_old.html
{% extends 'layouts/default/page.html' %}
{% load static %}

{% load i18n %}

{%block style%}
	.welcomeClass
	{
		display:flex;
		justify-content: center;
		text-align: center;
		margin-top: 10%;
	}
	@import url('https://fonts.googleapis.com/css?family=Exo:400,700');

*{
    margin: 0px;
    padding: 0px;
}

body{
    font-family: 'Exo', sans-serif;
}


.context {
    width: 100%;
    position: absolute;
    top:50vh;
    
}

.context h1{
    text-align: center;
    color: #000000;
    font-size: 50px;
}


.area{
    background: #d2e9f6;  
    width: 100%;
    height:100vh;
    
   
}

.circles{
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.circles li{
    position: absolute;
    display: block;
    list-style: none;
    width: 20px;
    height: 20px;
    background: rgba(232,155,223, 0.3);
    animation: animate 25s linear infinite;
    bottom: -150px;
    
}

.circles li:nth-child(1){
    left: 25%;
    width: 80px;
    height: 80px;
    animation-delay: 0s;
}


.circles li:nth-child(2){
    left: 10%;
    width: 20px;
    height: 20px;
    animation-delay: 2s;
    animation-duration: 12s;
}

.circles li:nth-child(3){
    left: 70%;
    width: 20px;
    height: 20px;
    animation-delay: 4s;
}

.circles li:nth-child(4){
    left: 40%;
    width: 60px;
    height: 60px;
    animation-delay: 0s;
    animation-duration: 18s;
}

.circles li:nth-child(5){
    left: 65%;
    width: 20px;
    height: 20px;
    animation-delay: 0s;
}

.circles li:nth-child(6){
    left: 75%;
    width: 110px;
    height: 110px;
    animation-delay: 3s;
}

.circles li:nth-child(7){
    left: 35%;
    width: 150px;
    height: 150px;
    animation-delay: 7s;
}

.circles li:nth-child(8){
    left: 50%;
    width: 25px;
    height: 25px;
    animation-delay: 15s;
    animation-duration: 45s;
}

.circles li:nth-child(9){
    left: 20%;
    width: 15px;
    height: 15px;
    animation-delay: 2s;
    animation-duration: 35s;
}

.circles li:nth-child(10){
    left: 85%;
    width: 150px;
    height: 150px;
    animation-delay: 0s;
    animation-duration: 11s;
}



@keyframes animate {

    0%{
        transform: translateY(0) rotate(0deg);
        opacity: 1;
        border-radius: 0;
    }

    100%{
        transform: translateY(-1000px) rotate(720deg);
        opacity: 0;
        border-radius: 50%;
    }

}
body
{
    background-color: #d2e9f6;
}
nav
{
	z-index:99999;
}
.blockquote
{
	display:flex;
	justify-content:center;
	text-align: center;
}
blockquote cite
{
	font-size:18px;
}
.dashboard
{
	display:flex;
	justify-content:center;
	text-align: center;
	z-index:9999999;	
}
a.dashboard 
{
	z-index:inherit;
	text-decoration:none;
	color:#000000;
    font-size: 20px;
    border: 2px #e89bdf ;
    border-radius: 24px;
    padding:8px;
    box-shadow: 2px 2px;
    background: rgba(232,155,223, 0.3);
}
a:hover 
{
	background-color: rgb(188,209,244);
}

a:active {
  background-color: rgb(188,209,244);
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}

div.headinglogo
{
	display: block;
	justify-content: center;
	text-align: center;
}
div.heading
{
	display: inline-block;
	width:100%
}
p.headingp
{
	font-size:2em;
	text-shadow: 1px 1px 1px;
}
div.logo
{
	display: inline-block;
	width: 100%;
	margin-top:5%;
}
section.features
{
	display:flex;
	align-items: center;
	padding:2rem 0;
	width:100%;
	background-color:#000000;
	color:#FFFFFF;
}
.infoPicture
{
	width:220px;
	height: 220px;
}
.leftmost
{
	padding-left:12%;
}
.info
{
	color:#FFFFFF;
	text-align:left;
}
.descriptionDiv
{
	margin: 0 auto;
	padding-left:5%;
	display:block;
	width:70%;

}
.description
{
	padding-top:2rem;
	text-align:justify;
	color:#000000;
	text-align: left;
	font-size:20px;

}
.navbuttons
{
	text-decoration:none;
	color:#FFFFFF;
    font-size: 20px;
    <!-- border-radius: 24px; -->
    width:10%;
}
a.navbuttons
{
    margin:10px;
    border: 1px solid #FFFFFF;
    text-align:center;
}
{%endblock %}

{%block script %}

{%endblock %}

{% block content %}

    {% if request.user.is_authenticated %}

		<div class="context"> 		
			<h1>Welcome Back {{ request.user.username|title }}!</h1>
			<blockquote class="blockquote"><q>It takes as much energy to wish as it does to plan</q><br>
				<cite class="citation" title="Source Title">  ~ Eleanor Roosevelt</cite>
			</blockquote>
			<!-- <button type="button" class="dashboard" href="https://www.google.com/">Head to Dashboard!</button>
			  -->
			<span class="dashboard">
				<a class="dashboard" href="{% url 'dashboard:dashboard_page' %}">{% trans 'Go to Dashboard' %}</a>
			</span>
		</div>
		<div class="area" >
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>
    	</div >
    {% else %}
        	<div class="headinglogo">
        		<div class="logo">
        			<img src="{% static 'loginIcon.png' %}" alt="icon">
        		</div>
        		<div class="heading"> 
        			<p class="headingp">Personal Management System</p>
        		</div>
        	</div>
        	<section class="features">
        		<div class="container">
        			<div class="row">
        				<div class="col  leftmost">
        					<img class="infoPicture"src="{% static '1.png' %}" alt="Easy To Use">
        					<h3> Easy To Use</h3>
        					<p class="info">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel felis quis nisi finibus tincidunt a a nisi. Sed a lorem sollicitudin, vestibulum nulla vel, mollis eros. Curabitur malesuada luctus venenatis.</p>
        				</div>
        				<div class="col ">
        					<img class="infoPicture"src="{% static '2.png' %}" alt="Never Miss a thing">
        					<h3> Never miss a thing</h3>
        					<p class="info">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel felis quis nisi finibus tincidunt a a nisi. Sed a lorem sollicitudin, vestibulum nulla vel, mollis eros. Curabitur malesuada luctus venenatis.</p>
        				</div>
        				<div class="col ">
        					<img class="infoPicture"src="{% static '3.png' %}" alt="Be organized">
        					<h3> Be organized</h3>
        					<p class="info">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel felis quis nisi finibus tincidunt a a nisi. Sed a lorem sollicitudin, vestibulum nulla vel, mollis eros. Curabitur malesuada luctus venenatis.</p>
        				</div>
        			</div>
        			<div class="navbuttons container">
        				<div class="row">
        				<a class="navbuttons col" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        				<a class="navbuttons col" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
        			</div>
        		</div>
        	</section>
        	<div class="descriptionDiv">
        		<p class="description"><strong>Personal Management System</strong> for educators is a web-app that is specifically designed keeping the needs of educators in mind. It helps keep track of all things by giving them tools like to-do lists, notes, password tracking etc.
        		It also helps them manage their personal life by using tools that keep track of their bills annd payments and any issues they wish to rectify.
        		Keep track of administrative and academic work while also making time for yourself and your loved ones.  
        	</div>
    
    {% endif %}

{% endblock %}