src/PersonalManagementSystem/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from homeapp.views import homepage_view
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',homepage_view),

# ]
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView
from dashboard.views import dashboard_view
from todolist.views import CreateToDoListView, taskJson, deleteJson, markItemAsCompleted, editTask
from issues.views import IssueView, issuesJson, deleteIssue, editIssue
from issues.views import IssueView
from passwords.views import PasswordView, deletePassword, updatePassword
from schedules.views import ScheduleView
from bills.views import BillsView, deleteBill
from schedules.views import ScheduleView, deleteSchedule, editSchedule

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('dashboard/',include('dashboard.urls')),

    path('todolist/',CreateToDoListView.as_view()),
    path('todolist/json/<int:task>',taskJson,name='taskJson'),
    path('todolist/delete/<int:task>',deleteJson,name='deleteJson'),
    path('todolist/update/<int:task>',markItemAsCompleted,name='markItemAsCompleted'),
    path('todolist/edit/<int:task>',editTask,name='editTask'),

    path('issues/',IssueView.as_view()),
    path('issues/json/<int:issue>',issuesJson,name='issuesJson'),
    path('issues/delete/<int:issue>',deleteIssue,name='deleteIssue'),
    path('issues/edit/<int:issue>',editIssue,name='editIssue'),

    path('passwords/',PasswordView.as_view()),
    path('passwords/delete/<int:password>',deletePassword,name='deletePassword'),
    path('passwords/update/<int:password>',updatePassword,name='updatePassword'),

    path('schedules/',ScheduleView.as_view()),
    path('schedules/delete/<int:schedule>',deleteSchedule,name='deleteSchedule'),
    path('schedules/edit/<int:schedule>',editSchedule,name='editSchedule'),

    path('bills/',BillsView.as_view()),
    path('bills/delete/<int:bill>',deleteBill,name='deleteBill'),

   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

src/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

src/dashboard/urls.py
from django.urls import path
app_name = 'dashboard'
from dashboard.views import dashboard_view,urlBillsPerMonth
urlpatterns = [
    path('main/', dashboard_view, name='dashboard_page'),
    path('main/year/<int:specified_year>',urlBillsPerMonth,name='specific_year'),
]

src/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class ToDoList(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	taskName = models.CharField(max_length=10000)
	taskDescription = models.CharField(max_length=10000,blank=True)
	date_added = models.DateTimeField(auto_now_add=True)
	taskTypes_list = (('Academic','Academic'),('Administrative', 'Administrative'),('Personal','Personal'),('Research','Research'))
	taskType = models.CharField(max_length=255,choices=taskTypes_list,default='Academic')
	mark_as_complete = models.BooleanField(default=False)
	
	def __str__(self):
		return self.taskName

src/todolist/forms.py
from .models import ToDoList
from django.forms import ModelForm
from django.db import models


class ToDoListForm(ModelForm):
	class Meta:
		model = ToDoList
		fields = ['taskName','taskDescription','taskType']
		labels = {
			'taskName':'Task Name',
			'taskDescription':'Task Description',
			'taskType':'Task Type'
		}
		

src/todolist/views.py
from django.shortcuts import render
from .models import ToDoList
from django.contrib.auth import authenticate
from .forms import ToDoListForm
from django.views.generic import View, FormView, TemplateView
from django.utils import timezone
from django.utils import http
from django.shortcuts import redirect
from django.conf import settings
from django.core import serializers
import json
from django.http import JsonResponse, HttpResponse

# Create your views here.
class CreateToDoListView(TemplateView):
	def get(self, request):
		if request.user.is_authenticated:
			context={}
			current_todo = self.get_current_todolist(request)
			if current_todo is not None:
				# context['todolist'] = current_todo
				context=self.sortCurrentTodo(current_todo)
			form = ToDoListForm()
			context['form']=form
			return  render(request,'todolistdisplay.html',context)
		else:
			return redirect(settings.LOGIN_REDIRECT_URL)

	def post(self, request):
		print(self.request.user.id)
		form = ToDoListForm(request.POST)
		context={}
		if form.is_valid():
			taskName= request.POST.get('taskName')
			taskType= request.POST.get('taskType')
			taskDescription = request.POST.get('taskDescription')
			date_added = timezone.now()
			user= request.user
			task= ToDoList(user=user,
				taskName=taskName,
				taskDescription=taskDescription,
				date_added=date_added,
				taskType=taskType,
				mark_as_complete=False)
			task.save()
			current_todo = self.get_current_todolist(request)
			if current_todo is not None:
				# context['todolist'] = current_todo
				context=self.sortCurrentTodo(current_todo)
			form = ToDoListForm()
			context['form']=form
			return render(request,'todolistdisplay.html',context)
	def get_current_todolist(self,request):
		response=ToDoList.objects.filter(user=request.user.id)
		if response is None:
			return None
		else:
			return response
	def sortCurrentTodo(self,current_todo):
		sortedCurrentTodo={'Academic':list([]),'Administrative': list([]),'Personal':list([]),'Research':list([])}
		for task in current_todo:
			sortedCurrentTodo[task.taskType].append(task)
		return sortedCurrentTodo
def taskJson(request,task):
	if request.user.is_authenticated:
		taskObj = ToDoList.objects.filter(id=task)
		jsonitems = serializers.serialize("json",taskObj)
		jsonitems = json.loads(jsonitems)
		return JsonResponse(jsonitems,safe=False)
	else:
		return redirect(settings.LOGIN_REDIRECT_URL)
def deleteJson(request,task):
	if request.user.is_authenticated:
		deleted=ToDoList.objects.filter(id=task).delete()
		return HttpResponse('')
	else:
		return redirect(settings.LOGIN_REDIRECT_URL)
def markItemAsCompleted(request,task):
	if request.user.is_authenticated:
		response_task=ToDoList.objects.filter(id=task)
		if response_task[0].mark_as_complete==True:
			response_task.update(mark_as_complete= False)
		else:
			response_task.update(mark_as_complete= True)
		return HttpResponse('')
	else:
		return redirect(settings.LOGIN_REDIRECT_URL)
def editTask(request,task):
	if request.user.is_authenticated:
		taskObj =ToDoList.objects.filter(id=task)
		jsonitems = serializers.serialize("json",taskObj)
		jsonitems = json.loads(jsonitems)
		return JsonResponse(jsonitems,safe=False)
	else:
		return redirect(settings.LOGIN_REDIRECT_URL)

src/todolist/templates/todolistdisplay_old.html
<html lang="en">
	<head>
		<script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
		<style>
			.taskDetails
			{
				display:none;
				border:2px solid #000000;
				max-width:30rem;
				text-align: center;
				margin:10px;
			}
			.boxes
			{
				border:2px solid #000000;
				margin:20px;
			}
			.boxes button
			{
				margin:10px;
			}
		</style>
		<style>
        @import url(//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css);
        }
            @import url(https://fonts.googleapis.com/css?family=Titillium+Web:300);
            .fa-2x {
            font-size: 2em;
            }
            .fa {
            position: relative;
            display: table-cell;
            width: 60px;
            height: 36px;
            text-align: center;
            vertical-align: middle;
            font-size:20px;
        }
        .main-menu:hover,nav.main-menu.expanded 
        {
            width:250px;
            overflow:visible;
        }
        .main-menu 
        {
            background:#212121;
            border-right:1px solid #e5e5e5;
            position:absolute;
            top:0;
            bottom:0;
            height:100%;
            left:0;
            width:250px;
            /*overflow:hidden;*/
            -webkit-transition:width .05s linear;
            transition:width .05s linear;
            -webkit-transform:translateZ(0) scale(1,1);
            z-index:1000;
        }
        .main-menu>ul 
        {
            margin:7px 0;
        }
        .main-menu li 
        {
            position:relative;
            display:block;
            width:250px;
        }
        .main-menu li>a 
        {
            position:relative;
            display:table;
            border-collapse:collapse;
            border-spacing:0;
            color:#999;
             font-family: arial;
            font-size: 14px;
            text-decoration:none;
            -webkit-transform:translateZ(0) scale(1,1);
            -webkit-transition:all .1s linear;
            transition:all .1s linear;     
        }
        .main-menu .nav-icon 
        {
            position:relative;
            display:table-cell;
            width:60px;
            height:36px;
            text-align:center;
            vertical-align:middle;
            font-size:18px;
        }
        .main-menu .nav-text 
        {
            position:relative;
            display:table-cell;
            vertical-align:middle;
            width:190px;
            font-family: 'Titillium Web', sans-serif;
        }
        .main-menu>ul.logout 
        {
            position:absolute;
            left:0;
            bottom:0;
        }
        .no-touch .scrollable.hover 
        {
            overflow-y:hidden;
        }
        .no-touch .scrollable.hover:hover 
        {
            overflow-y:auto;
            overflow:visible;
        }
        a:hover,a:focus 
        {
            text-decoration:none;
        }
        nav 
        {
            -webkit-user-select:none;
            -moz-user-select:none;
            -ms-user-select:none;
            -o-user-select:none;
            user-select:none;
            /*height:100%;*/
        }

        nav ul,nav li 
        {
            outline:0;
            margin:0;
            padding:0;
        }
        .main-menu li:hover>a,nav.main-menu li.active>a,.dropdown-menu>li>a:hover,.dropdown-menu>li>a:focus,.dropdown-menu>.active>a,.dropdown-menu>.active>a:hover,.dropdown-menu>.active>a:focus,.no-touch .dashboard-page nav.dashboard-menu ul li:hover a,.dashboard-page nav.dashboard-menu ul li.active a 
        {
            color:#fff;
            background-color:#5fa2db;
        }
        .area 
        {
            margin-left:3.7rem;
            background-color:#d2e9f6; 
            height: 100%;
        }
        @font-face 
        {
            font-family: 'Titillium Web';
            font-style: normal;
            font-weight: 300;
            src: local('Titillium WebLight'), local('TitilliumWeb-Light'), url(http://themes.googleusercontent.com/static/fonts/titilliumweb/v2/anMUvcNT0H1YN4FII8wpr24bNCNEoFTpS2BTjF6FB5E.woff) format('woff');
        }
        .maincontent
        {
        	margin-left:15rem;
        }
        .formclass
        {
        	border:2px solid #000000;
        	margin-left: 2rem; 
        	display:none;
        }

    	</style>
	</head>
	<body>
		<nav class="main-menu">
            <ul>
                <li>
                    <a href="/">
                        <i class="fa fa-home fa-2x"></i>
                        <span class="nav-text">
                            Home
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'dashboard:dashboard_page' %}">
                        <i class="fa fa-tachometer fa-2x"></i>
                        <span class="nav-text">
                            Dashboard
                        </span>
                    </a>
                  
                </li>
                <li class="has-subnav">
                    <a href="/todolist">
                        <i class="fa fa-list fa-2x"></i>
                        <span class="nav-text">
                            To-Do List
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="#">
                       <i class="fa fa-calendar fa-2x"></i>
                        <span class="nav-text">
                            Schedule
                        </span>
                    </a>
                    
                    
                </li>
                <li class="has-subnav">
                    <a href="#">
                       <i class="fa fa-laptop fa-2x"></i>
                        <span class="nav-text">
                            Passwords
                        </span>
                    </a>
                   
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-credit-card fa-2x"></i>
                        <span class="nav-text">
                            Bills and Payments
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-exclamation fa-2x"></i>
                        <span class="nav-text">
                           Issues
                        </span>
                    </a>
                </li>
                <li>
                   <a href="{% url 'accounts:change_password' %}">
                       <i class="fa fa-wrench fa-2x"></i>
                        <span class="nav-text">
                            Change Password
                        </span>
                    </a>
                </li>
                <li>
                   <a href="{% url 'accounts:change_profile' %}">
                        <i class="fa fa-user fa-2x"></i>
                        <span class="nav-text">
                            Change Profile
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:change_email' %}">
                       <i class="fa fa-cog fa-2x"></i>
                        <span class="nav-text">
                            Change Email
                        </span>
                    </a>
                </li> 
            </ul>
            <ul class="logout">
                <li>
                   <a href="{% url 'accounts:log_out' %}">
                         <i class="fa fa-power-off fa-2x"></i>
                        <span class="nav-text">
                            Logout
                        </span>
                    </a>
                </li>  
            </ul>
        </nav>
        <div class="maincontent">
			<div class="boxes">
				<h3>Academic</h3>
				{% for task in Academic %}
						<button type="button" class="" id="{{task.id}}" onclick="fetch(this.id)">{{task.taskName}}</button>
				{% endfor %}
				<br>
				<button type="button" class="addButtons" id="academic_add" onclick="showForm(this.id)">Add Task</button>
			</div>
			<div class="boxes">
				<h3>Personal</h3>
				{% for task in Personal %}
						<button type="button" class="" id="{{task.id}}" onclick="fetch(this.id)">{{task.taskName}}</button>
				{% endfor %}<br>
				<button type="button" class="addButtons" id="personal_add" onclick="showForm(this.id)">Add Task</button>
			</div>
			<div class="boxes">
				<h3>Administrative</h3>
				{% for task in Administrative %}
						<button type="button" class="" id="{{task.id}}" onclick="fetch(this.id)">{{task.taskName}}</button>
				{% endfor %}<br>
				<button type="button" class="addButtons" id="administrative_add" onclick="showForm(this.id)">Add Task</button>
			</div>
			<div class="boxes">
				<h3>Research</h3>
				{% for task in Research %}
						<button type="button" class="" id="{{task.id}}" onclick="fetch(this.id)">{{task.taskName}}</button>
				{% endfor %}<br>
				<button type="button" class="addButtons" id="research_add" onclick="showForm(this.id)">Add Task</button>
			</div>
			<div class="taskDetails" id="taskdetailsdiv">
			</div>
			<div class="formclass" id="divformclass">
				<form method="post">{% csrf_token %}
					{{ form.as_p}}
					<input type="submit" name="submit" value="Submit" onclick="hideForm()"/>
					<button type="button"  onclick="hideForm()">Cancel</button>
				</form>
			</div>
		</div> 
	</body>
</html>
<script type="text/javascript">
	function hideForm()
	{
		var div= document.getElementById("divformclass");
		div.style.display="none";
	}
	function showForm(buttonID)
	{	
		var div= document.getElementById("divformclass");
		div.style.display="block";
		var combobox = document.getElementById("id_taskType");
		if (buttonID=="research_add")
		{
			combobox.selectedIndex=3;
		}
		else if (buttonID=="administrative_add")
		{
			combobox.selectedIndex=1;
		}
		else if (buttonID=="personal_add")
		{
			combobox.selectedIndex=2;
		}
		else if (buttonID=="academic_add")
		{
			combobox.selectedIndex=0;
		}
	}
	function showdescription()
	{
		var div= document.getElementById("taskdetailsdiv");
		console.log(window.getComputedStyle(div));
		div.style.display="block";
	}
	function hidedescription()
	{
		var div = document.getElementById("taskdetailsdiv");
		div.style.display ="none";
	}
	function fetch(taskID)
	{
		$.getJSON("json/" + taskID, function (items) {
			taskWindow =  document.getElementById("taskdetailsdiv");
			items=items[0];
			console.log(items);
			fields=items.fields;
			pk=items.pk;
			console.log(pk);
			var taskDate=fields.date_added.slice(0,10);
			taskWindow.innerHTML = "<label>Task Name:"+fields.taskName+"</label><br>"+"<label>Task Description:"+fields.taskDescription+"</label><br>"+ "<label>Category:"+fields.taskType+"</label><br>"+"<label>Date Added: "+taskDate+"</label><br>"+"<button type='button' onclick='hidedescription()'>Close</button>"+"<button type='button' onclick='deleteItem("+pk+")'>Delete Task</button>";
			taskWindow.style.display="block";
		});

	}
	function deleteItem(taskID)
	{
		console.log(taskID);
		button=document.getElementById(taskID);
		button.parentNode.removeChild(button);
		hidedescription()
		$.getJSON("delete/" + taskID, function () {});
	}
</script>