src/PersonalManagementSystem/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from homeapp.views import homepage_view
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',homepage_view),

# ]
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView
from dashboard.views import dashboard_view
from todolist.views import CreateToDoListView, taskJson, deleteJson, markItemAsCompleted, editTask
from issues.views import IssueView, issuesJson, deleteIssue, editIssue
from issues.views import IssueView
from passwords.views import PasswordView, deletePassword, updatePassword
from schedules.views import ScheduleView
from bills.views import BillsView, deleteBill
from schedules.views import ScheduleView, deleteSchedule, editSchedule

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('dashboard/',include('dashboard.urls')),

    path('todolist/',CreateToDoListView.as_view()),
    path('todolist/json/<int:task>',taskJson,name='taskJson'),
    path('todolist/delete/<int:task>',deleteJson,name='deleteJson'),
    path('todolist/update/<int:task>',markItemAsCompleted,name='markItemAsCompleted'),
    path('todolist/edit/<int:task>',editTask,name='editTask'),

    path('issues/',IssueView.as_view()),
    path('issues/json/<int:issue>',issuesJson,name='issuesJson'),
    path('issues/delete/<int:issue>',deleteIssue,name='deleteIssue'),
    path('issues/edit/<int:issue>',editIssue,name='editIssue'),

    path('passwords/',PasswordView.as_view()),
    path('passwords/delete/<int:password>',deletePassword,name='deletePassword'),
    path('passwords/update/<int:password>',updatePassword,name='updatePassword'),

    path('schedules/',ScheduleView.as_view()),
    path('schedules/delete/<int:schedule>',deleteSchedule,name='deleteSchedule'),
    path('schedules/edit/<int:schedule>',editSchedule,name='editSchedule'),

    path('bills/',BillsView.as_view()),
    path('bills/delete/<int:bill>',deleteBill,name='deleteBill'),

   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

src/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
)
from .models import Activation


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/log_in.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        # return redirect(settings.LOGIN_REDIRECT_URL) #Old code, redirects to Homepage after login
        return redirect('/dashboard/main')    #New page redirects to dashboard after login


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('You are signed up. To activate the account, follow the link sent to the mail.'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('You are successfully signed up!'))

        return redirect("accounts:log_in")


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account!'))

        return redirect('accounts:log_in')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = Activation()
        act.code = code
        act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('A new activation code has been sent to your email address.'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))

        if isinstance(uid, bytes):
            uid = uid.decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Change the email
        user = act.user
        user.email = act.email
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully changed your email!'))

        return redirect('accounts:change_email')


class RemindUsernameView(GuestOnlyView, FormView):
    template_name = 'accounts/remind_username.html'
    form_class = RemindUsernameForm

    def form_valid(self, form):
        user = form.user_cache
        send_forgotten_username_email(user.email, user.username)

        messages.success(self.request, _('Your username has been successfully sent to your email.'))

        return redirect('accounts:remind_username')


class ChangePasswordView(BasePasswordChangeView):
    template_name = 'accounts/profile/change_password.html'

    def form_valid(self, form):
        # Change the password
        user = form.save()

        # Re-authentication
        login(self.request, user)

src/accounts/templates/accounts/log_in.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <link rel="icon" href="{% static 'loginIcon.png' %}">

    <title>Log In</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'css/styles.css' %}" rel="stylesheet"> -->
    <style>
        /** 
        {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }*/
        body
        {
            /*background: url("{%static 'bgmirror.png'%}") ;*/
            /*background-size: 1707px 818px;*/
            /*background-repeat:no-repeat;
            background-size: cover;
            overflow-y:hidden;*/
            /*background-size: contain;*/
            /*background-image: url(https://unsplash.com/photos/_Hiv8JKpHzQ);*/
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }
        container-fluid mt-3 
        {
            font-family: "Poppins", sans-serif;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            /*perspective: none;*/
        }
        .container 
        {
            min-width: 50%;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .cardx 
        {
            /*transform-style: preserve-3d;*/
            margin-top:25px;
            min-height: 75vh;
            min-width: 32rem;
            border-radius: 30px;
            padding: 0rem 0rem 0rem 3rem;
            padding-left:27px;
            box-shadow: 0 20px 20px rgba(0, 0, 0, 0.2), 0px 0px 50px rgba(0, 0, 0, 0.2);
            /*display:inline-block;*/
        }

        .iconclass 
        {
            min-height: 35vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .iconclass img 
        {
            /*width: 20rem;*/
            width: 10rem;
            z-index: 2;
        }
        .circle 
        {
            width: 15rem;
            height: 15rem;
            /*background: linear-gradient(to right, rgba(245, 70, 66, 0.75), rgba(8, 83, 156, 0.75)           );*/
            position: absolute;
            border-radius: 50%;
            z-index: 1;
        }
        .info h1 
        {
            font-size: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .sizes 
        {
            display: flex;
            justify-content: space-between;
            transition: all 0.75s ease-out;
        }

        /*.sizes a 
        {
            padding: 0.5rem 2rem;
            background: none;
            border: none;
            box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.2);
            border-radius: 30px;
            cursor: pointer;
            font-weight: bold;
            color: #585858;
        }*/
        /*a.active 
        {
            background: #585858;
            color: white;
        }*/
        .jumbotron 
        {
            background: url(path/to/image.jpg) fixed center no-repeat;
            background-size: cover;
        }
        .btn
        {
            display: block;
            margin: 0 auto;
            margin-bottom:15px;
            width:40%;
        }
        #forgotpassword
        {
            margin-bottom:10px;   
        }
        label
        {
            display:none;
        }
        label.form-check-label
        {
            display:inline-block;
        }

.area{
    background: #d2e9f6;  
    width: 100%;
    /*height:100vh;*/
    /*overflow-y: hidden;*/
   
}

.circles{
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.circles li{
    position: absolute;
    display: block;
    list-style: none;
    width: 20px;
    height: 20px;
    background: rgba(0,0,0, 0.3);
    animation: animate 25s linear infinite;
    bottom: -150px;
    
}

.circles li:nth-child(1){
    left: 25%;
    width: 80px;
    height: 80px;
    animation-delay: 0s;
}


.circles li:nth-child(2){
    left: 10%;
    width: 20px;
    height: 20px;
    animation-delay: 2s;
    animation-duration: 12s;
}

.circles li:nth-child(3){
    left: 70%;
    width: 20px;
    height: 20px;
    animation-delay: 3s;
}

.circles li:nth-child(4){
    left: 40%;
    width: 60px;
    height: 60px;
    animation-delay: 0s;
    animation-duration: 18s;
}

.circles li:nth-child(5){
    left: 65%;
    width: 20px;
    height: 20px;
    animation-delay: 0s;
}

.circles li:nth-child(6){
    left: 75%;
    width: 110px;
    height: 110px;
    animation-delay: 3s;
}

.circles li:nth-child(7){
    left: 6%;
    width: 150px;
    height: 150px;
    animation-delay: 2s;
    animation-duration:16s;
}

.circles li:nth-child(8){
    left: 10%;
    width: 40px;
    height: 45px;
    animation-delay: 0s;
    animation-duration: 30s;
}

.circles li:nth-child(9){
    left: 20%;
    width: 15px;
    height: 15px;
    animation-delay: 2s;
    animation-duration: 35s;
}

.circles li:nth-child(10){
    left: 85%;
    width: 150px;
    height: 150px;
    animation-delay: 0s;
    animation-duration: 11s;
}



@keyframes animate {

    0%{
        transform: translateY(0) rotate(0deg);
        opacity: 1;
        border-radius: 0;
    }

    100%{
        transform: translateY(-1000px) rotate(720deg);
        opacity: 0;
        border-radius: 50%;
    }

}

.jumbotron
{
    z-index:99999;   
}
.container
{
    z-index:9999999;
}

.iconclass
{
    z-index:9999999;
}
.login
{
    z-index:9999999;
}
.cardx
{
    z-index: 9999999;
    background-color: #FFFFFF;
}

.card_left
{
    display: inline-block;
    min-width:22rem;
    /*flex: 1;*/
    /*float: left;*/
    /*width:50%;*/
    z-index:9999999;

}
.card_right
{
    display: inline-block;
    /*background-image: url("{% static 'bg_login.jfif' %}");*/
    min-width: 20rem;
    float: right;
    /*width: 50%;*/
    padding: 0px;
    z-index:9999999;
}
.image_right
{
    width: 490px;
    height: 615px;
    padding-left:30px;
    padding-right:0px;
    margin-right: 0px;
    border-radius: 0px 30px 30px 0px;
}


</style>
</head>

<body>
 
<!-- <nav class="navbar navbar-expand-md navbar-dark bg-dark static-top"> -->

    <!-- <a class="navbar-brand" href="/">{% trans 'Home' %}</a> -->
<!-- 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button> -->

<!--     <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
            </li>
        </ul>
    </div>

</nav>
 -->
<div class="container-fluid mt-3">

    {% bootstrap_messages %}
    <div class="jumbotron">
    <div class="container">
        <div class="cardx">
            <div class="card_left">
                <div class="iconclass">
                    <a href="/"><img src="{% static 'loginIcon.png' %}" alt="icon"></a>
                </div>
                <div class="info">
                    <h1 class="title">Personal Management System</h1>
                </div>
                <br>
                <div class="login">
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button class="btn btn-primary">{% trans 'Log in' %}</button>
                    </form>
                </div>
                <div class="sizes">
                        <a href="{% url 'accounts:restore_password' %}" id="forgotpassword">{% trans 'Forgot your password?' %}</a><br>
                        <a href="{% url 'accounts:sign_up' %}" id="forgotpassword">{% trans 'New User? ' %}</a>
                </div>
            </div>
            <div class="card_right">
                <img class="image_right"src="{% static 'bg_login.jfif' %}" alt="icon">
            </div>
        </div>
    </div>
    </div>

</div>
<div class="area" >
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>
        </div >
<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

src/accounts/templates/accounts/log_out.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'Logged out' %}</h4>

    <p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>

    <p>
        <a href="{% url 'accounts:log_in' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

src/accounts/templates/accounts/remind_username.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Remind a username' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

src/accounts/templates/accounts/resend_activation_code.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Resend an activation code' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

src/accounts/templates/accounts/restore_password.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

src/accounts/templates/accounts/restore_password_confirm.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    {% if validlink %}

        <p>
            {% trans 'Please enter your new password twice so we can verify you typed it in correctly.' %}
        </p>

        <form method="post">

            {% csrf_token %}
            {% bootstrap_form form %}

            <button class="btn btn-success">{% trans 'Change' %}</button>

        </form>

    {% else %}

        <div class="alert alert-danger">
            {% trans 'The password reset link was invalid, possibly because it has already been used. Please request a new password reset.' %}
        </div>

    {% endif %}

{% endblock %}

src/accounts/templates/accounts/restore_password_done.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'Restore password' %}</h4>

    <div>
        {% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered." %}
        {% trans 'You should receive them shortly.' %}

        <br>

        {% trans "If you don't receive an email, please make sure you've entered the address you signed up with, and check your spam folder." %}
    </div>

{% endblock %}

src/accounts/templates/accounts/sign_up.html
{% extends 'layouts/default/page.html' %}
{% load bootstrap4 %}
{% load static %}	
{% load i18n %}
{% block title %}Register{% endblock %}

{%block style%}
	body
	{
		background: url("{%static 'bg_reg.png'%}") ;
		display:flex;
		align-items: center;
		justify-content: center;
	}
	.card
	{
		box-sizing: border-box;
	}
	.card
	{
		margin-top: 1.5%;
		display: flex;
		border:none;
		align-items: center;
		justify-content: center;
		min-width: 32%;
		font-weight:bold;
		background-color:rgba(149,179,171,0.8);
		border-radius: 50px;
		padding: 15px 0px;
		padding-bottom: 0px;
	}
	.register h4
	{
		text-align: center;
	}
	.form-text li:nth-child(1) 
	{
	    display:none;
	}
	a
	{
		font-weight:normal;
		text-align:right;
	}
	#gohome
	{
		padding: 10px 55px 0px 0px;
	}
	#gologin
	{
		padding: 10px 0px 0px 55px;
	}
	.btn
	{
		margin-bottom: 3px;
	}
{%endblock%}

{% block content %}

    <div class="card">
	    <form class="register" method="post">	
    		<h4>{% trans 'Create an account' %}</h4>

	        {% csrf_token %}
	        {% bootstrap_form form %}
	        <button class="btn btn-success">{% trans 'Create' %}</button>
	    </form>
	    <p>
	    <a href="/" id="gohome">{% trans 'Go back to Homepage' %}</a>
	    <a href="{% url 'accounts:log_in' %}" id="gologin">{% trans 'Already a User? ' %}</a></p>
	</div>
{% endblock %}